data_filepath: ../data/yaw/split_1
epochs: 20
gamma: 0.5
if_cuda: True
log_dir: log_yaw
lr: 0.00005
lr_schedule:
- 5
- 10
- 15
num_gpus: 1
num_workers: 8
seed: 1
test_batch: 500
train_batch: 500
val_batch: 500