data_filepath: ../data/yaw/split_1
epochs: 100
gamma: 0.5
if_cuda: True
log_dir: log_yaw
lr: 0.000001
lr_schedule:
- 20
- 40
- 60
- 80
num_gpus: 1
num_workers: 8
seed: 1
test_batch: 500
train_batch: 500
val_batch: 500