data_filepath: ../data/thrust/split_3
epochs: 100
gamma: 0.5
if_cuda: True
log_dir: log_thrust
lr: 0.00005
lr_schedule:
- 20
- 40
- 60
- 80
num_gpus: 1
num_workers: 8
seed: 1
test_batch: 500
train_batch: 500
val_batch: 500