data_filepath: data
epochs: 100
gamma: 0.8
if_cuda: True
log_dir: log/log_yaw
lr: 0.00005
lr_schedule:
- 50
- 80
num_gpus: 1
num_workers: 8
seed: 1234
test_batch: 100
train_batch: 500
val_batch: 100
role: yaw