data_filepath: data
epochs: 500
gamma: 0.9
if_cuda: True
log_dir: log
lr: 0.0005 # should be 1
lr_schedule:
- 50
- 100
- 200
- 300
num_gpus: 1
num_workers: 8
seed: 1234
test_batch: 100
train_batch: 500
val_batch: 100
role: pitch