data_filepath: data/seed_3
epochs: 100
gamma: 0.5
if_cuda: True
log_dir: log
lr: 0.00005
lr_schedule:
- 25
- 50
- 75 
num_gpus: 1
num_workers: 8
seed: 1
test_batch: 500
train_batch: 500
val_batch: 500