data_filepath: data
epochs: 200
gamma: 0.8
if_cuda: True
log_dir: log
lr: 0.0005
lr_schedule:
- 100
- 150
num_gpus: 1
num_workers: 8
seed: 1234
test_batch: 100
train_batch: 500
val_batch: 100
role: thrust