data_filepath: data
epochs: 50
gamma: 0.1
if_cuda: True
log_dir: log
lr: 0.0001
lr_schedule:
- 5
- 10
- 20
- 300
- 500
num_gpus: 1
num_workers: 8
seed: 1234
test_batch: 100
train_batch: 500
val_batch: 100